#pragma once

#define ANGEL3D_MOUSE_BUTTON_1         0
#define ANGEL3D_MOUSE_BUTTON_2         1
#define ANGEL3D_MOUSE_BUTTON_3         2
#define ANGEL3D_MOUSE_BUTTON_4         3
#define ANGEL3D_MOUSE_BUTTON_5         4
#define ANGEL3D_MOUSE_BUTTON_6         5
#define ANGEL3D_MOUSE_BUTTON_7         6
#define ANGEL3D_MOUSE_BUTTON_8         7
#define ANGEL3D_MOUSE_BUTTON_LAST      ANGEL3D_MOUSE_BUTTON_8
#define ANGEL3D_MOUSE_BUTTON_LEFT      ANGEL3D_MOUSE_BUTTON_1
#define ANGEL3D_MOUSE_BUTTON_RIGHT     ANGEL3D_MOUSE_BUTTON_2
#define ANGEL3D_MOUSE_BUTTON_MIDDLE    ANGEL3D_MOUSE_BUTTON_3